"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deletePet = exports.putPet = exports.postPet = exports.getPetById = exports.getAllPet = void 0;
const getPet_1 = require("./getPet");
Object.defineProperty(exports, "getAllPet", { enumerable: true, get: function () { return getPet_1.getAllPet; } });
Object.defineProperty(exports, "getPetById", { enumerable: true, get: function () { return getPet_1.getPetById; } });
const postPet_1 = require("./postPet");
Object.defineProperty(exports, "postPet", { enumerable: true, get: function () { return postPet_1.postPet; } });
const putPet_1 = require("./putPet");
Object.defineProperty(exports, "putPet", { enumerable: true, get: function () { return putPet_1.putPet; } });
const deletePet_1 = require("./deletePet");
Object.defineProperty(exports, "deletePet", { enumerable: true, get: function () { return deletePet_1.deletePet; } });
